### PR TITLE
Update forecasting.R

### PR DESCRIPTION
**Pull request by nfultz**
Light refactoring as I read your code. I generally recommend not using dplyr pipes in packages, but YMMV.

### CODE REVIEW

**Comment by laresbernardo** [comment]
Thanks @nfultz for your comments and codes.
Your first commit (https://github.com/laresbernardo/lares/pull/17/commits/9732ef5f6ab6a9007dff6e643b6c0b84834445b7) has been approved; thanks! Those were actually one of the first thinks I write with R (about 3 years ago!). The other two have issues so I can't branch them in yet :(

**Comment by laresbernardo** [comment]
Also added `rlang` dependency for `quo_is_null` function used

**Comment by nfultz** [comment]
Was it not already imported? You were using quosures?

**Comment by laresbernardo** [comment]
Plots aren't working with this merge: `Error in signif(plot$p, 4)`

**Comment by laresbernardo** [comment]
Fixed in my last commit: https://github.com/laresbernardo/lares/commit/2d2c11dbf77e9c66d886f6b7c25f8fe110cca7c6
You supressed `p` and `pcum` columns

**Pull request merged**
